project:
  type: book
  output-dir: _book

book:
  title: "WLM SDAR"
  subtitle: "World of Linear Models: Statistics & Data Analysis in R"
  author: 
    - name: "Антон Ангельгардт"
      email: "anton.angelgardt@gmail.com"
      # affiliation:
      #   - name: "HSE University"
  date: last-modified
  date-format: "MMMM D, YYYY"
  chapters:
    - index.qmd
    - signs.qmd
    - part: part-r.qmd
    - part: part-math.qmd
    - part: part-measure.qmd
    - part: part-prob.qmd
    - part: part-stats.qmd
    - part: part-desc.qmd
    - part: part-andan.qmd
    - part: part-randan.qmd
    - part: part-appendices.qmd
    - appendix-numbers.qmd
    - appendix-strings.qmd
    - appendix-kilobytes.qmd
    - appendix-memory.qmd
    - appendix-proglang.qmd
    - appendix-git.qmd
    - appendix-formulas.qmd
    - appendix-math-letters.qmd
    - appendix-design.qmd
    - references.qmd
  favicon: pics/design/favicon.png
  navbar: 
    title: "WLM SDAR"
    logo: pics/design/logo.png
    # left:
    # - text: ""
    #   href: 
    collapse: true
    background: gray-700

bibliography: references.bib

comments:
  hypothesis: true

highlight-style: github

format:
  html:
    cover-image: pics/design/book-cover.jpg
    theme: 
     light: [css/lightstyle.scss, css/custom.scss, css/tasklight.scss]
     dark: [css/darkstyle.scss, css/custom.scss, css/taskdark.scss]
  # pdf:
  #   documentclass: scrreprt
