project:
  type: book

book:
  title: "test-pdf-book"
  author: "Norah Jones"
  date: "2/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  # html:
  #   theme: cosmo
  pdf:
    documentclass: scrreprt
    include-in-header: 
      - file: _symbols.tex



