project:
  type: book
  output-dir: _book

metadata-files:
  - _metadata.yml

book:
  title: "WLM SDAR"
  # language: ru
  subtitle: "World of Linear Models: Statistics & Data Analysis in R"
  author: 
    - name: "Anton Angelgardt"
      email: "anton.angelgardt@gmail.com"
  version: "0.0.1"
  date: today
  
  chapters:
    - index.qmd
    - common-intro.qmd
    - common-signs.qmd
    - part: Debug
      chapters: 
      - debug_chapter.qmd
      - debug_quiz.qmd
      - debug_sheet.qmd
    - part: part-r.qmd
      chapters:
      - r-intro.qmd
      - r-datatypes.qmd
      - r-datastructures.qmd
      - r-functionsI.qmd
      - r-controlworkflow.qmd
      - r-functionsII.qmd
      - r-strings.qmd
      - r-datetime.qmd
      - r-data.qmd
      - r-preprocessbasic.qmd
      - r-preprocessadvanced.qmd
      - r-visbaser.qmd
      - r-visbasic.qmd
      - r-visadvanced.qmd
      - r-rmd.qmd
      - r-qmd.qmd
    - part: part-math.qmd
      chapters:
      - math-logic.qmd
      - math-set.qmd
      - math-comb.qmd
      - math-calculusI.qmd
      - math-calculusII.qmd
      - math-linalI.qmd
      - math-linalII.qmd
    - part: part-measures.qmd
      chapters:
      - measures-scales.qmd
      - measures-psymetI.qmd
      - measures-psymetII.qmd
      - measures-psymetIII.qmd
    - part: part-desc.qmd
      chapters:
      - desc-statintro.qmd
      - desc-centrtend.qmd
      - desc-variance.qmd
      - desc-distshape.qmd
      - desc-prodmetrics.qmd
    - part: part-prob.qmd
    - part: part-andan.qmd
      chapters:
      - andan-means.qmd
      - andan-categorical.qmd
      - andan-cor.qmd
      - andan-nonparam.qmd
      - andan-simplelinear.qmd
      - andan-multiplelinear.qmd
      - andan-polynomialreg.qmd
      - andan-svr.qmd
      - andan-regreg.qmd
      - andan-anova.qmd
      - andan-ancova.qmd
      - andan-manova.qmd
      - andan-regtrees.qmd
      - andan-regforest.qmd
      - andan-dist.qmd
      - andan-glm.qmd
      - andan-logreg.qmd
      - andan-multinomreg.qmd
      - andan-poisreg.qmd
      - andan-gam.qmd
      - andan-glmm.qmd
      - andan-glogmm.qmd
      - andan-gmultinommm.qmd
      - andan-svm.qmd
      - andan-classtrees.qmd
      - andan-classforest.qmd
      - andan-cluster.qmd
      - andan-fuzzycluster.qmd
      - andan-lda.qmd
      - andan-pca.qmd
      - andan-ica.qmd
      - andan-cca.qmd
      - andan-efa.qmd
      - andan-cfa.qmd
      - andan-sem.qmd
      - andan-path.qmd
      - andan-timeseries.qmd
    - common-outro.qmd
    - references.qmd
  appendices:
    - appendix-numbers.qmd
    - appendix-numbers-iron.qmd
    - appendix-strings-iron.qmd
    - appendix-memory-iron.qmd
    - appendix-proglang.qmd
    - appendix-formulas.qmd
    - appendix-git.qmd
    - appendix-research-design.qmd
    - appendix-design.qmd
    - appendix-math-letters.qmd
    - appendix-answers.qmd
    
  favicon: img/other/favicon.png

bibliography: references.bib

comments:
  hypothesis: true

highlight-style: 
  light: style/theme/light.theme
  dark: style/theme/dark.theme

format:
  html:
    title-block-banner: img/other/title-block-banner.jpg
    title-block-banner-color: "#f5f5f5"
    toc: true
    toc-depth: 4
    grid: 
      body-width: 900px
      sidebar-width: 210px
      margin-width: 210px
    cover-image: img/other/cover.jpg
    cover-image-alt: |
      Тут должна быть обложка книги, но что-то пошло не так...
    theme:
      light: [style/css/light.scss, style/css/common.scss]
      dark: [style/css/dark.scss, style/css/common.scss]
    code-overflow: scroll

editor: source
