project:
  type: book
  output-dir: _book

book:
  title: "WLM SDAR"
  language: ru
  subtitle: "World of Linear Models: Statistics & Data Analysis in R"
  author: 
    - name: "Anton Angelgardt"
      email: "anton.angelgardt@gmail.com"
  version: "0.0.1"
  date: today
  chapters:
    - index.qmd
    - part: Testing
      chapters: 
      - teststyle.qmd
      - testquiz.qmd
      - testsheet.qmd
    - part: R
      # chapters: 
      # - n.qmd
    - part: part-math.qmd
      # chapters: 
      # - n.qmd
    - part: part-measures.qmd
      # chapters: 
      # - n.qmd
    - part: part-prob.qmd
      # chapters: 
      # - n.qmd
    - part: part-desc.qmd
      # chapters: 
      # - n.qmd
    - part: part-andan.qmd
      # chapters: 
      # - n.qmd
    - references.qmd
  appendices:
    - appendix-numbers.qmd
    - appendix-answers.qmd
  favicon: img/other/favicon.png

bibliography: references.bib

comments:
  hypothesis: true

highlight-style: 
  light: style/theme/light.theme
  dark: style/theme/dark.theme

format:
  html:
    toc: true
    toc-depth: 4
    grid: 
      body-width: 900px
      sidebar-width: 210px
      margin-width: 210px
    cover-image: img/other/cover.jpg
    theme:
      light: style/css/light.scss
      dark: style/css/dark.scss

editor: source
