project:
  type: book
  output-dir: _book

book:
  title: "WLM SDAR"
  subtitle: "World of Linear Models: Statistics & Data Analysis in R"
  author: 
    - name: "Anton Angelgardt"
      email: "anton.angelgardt@gmail.com"
  version: "0.0.1"
  date: "5/8/2024"
  chapters:
    - index.qmd
    - teststyle.qmd
    - testquiz.qmd
    - testsheet.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
  favicon: img/other/favicon.png

bibliography: references.bib

comments:
  hypothesis: true

highlight-style: 
  light: ../style/theme/light.theme
  dark: ../style/theme/dark.theme

format:
  html:
    grid: 
      body-width: 900px
      sidebar-width: 210px
      margin-width: 210px
    cover-image: img/other/cover.jpg
    theme:
      light: ../style/css/light.scss
      dark: ../style/css/dark.scss

editor: source
